modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/better_christmas_chests/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "better_christmas_chests"
version = "${version}"
displayName = "Better Christmas Chests"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.better_christmas_chests]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_christmas_chests]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_christmas_chests]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
