modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/better_christmas_chests/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "better_christmas_chests"
version = "${version}"
displayName = "Better Christmas Chests"
authors = "MrMelon54"
description = "${description}"
logoFile = "icon.png"
displayURL = "https://mrmelon54.com/minecraft/better-christmas-chests"

[[dependencies.better_christmas_chests]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_minecraft_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_christmas_chests]]
modId = "infrastructury"
mandatory = true
versionRange = "[${infrastructury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_christmas_chests]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
